# .gitpod.yml

# Specify tasks to run on workspace startup
tasks:
  - name: Setup Crates and Tools
    init: |
      # Step 1: Install Anza
      sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
      
      # Step 2: Update PATH for Solana
      export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH"
      
      # Step 3: Install Anchor Version Manager (AVM) from the GitHub repository
      cargo install --git https://github.com/coral-xyz/anchor avm --force
      
      # Step 4: Set Rust version to 1.79.0
      rustup default 1.79.0

      # Step 5: Install AVM version 0.30.1
      avm install 0.30.1
