[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nonce = "4XSnD5eXrLPEuvEmN9hieF3ywBKXKPU2hogH7fUKYxmF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
